const todoData = [
    {   id: 0,
        name: "Clean Bedroom",
        description: "Need to clean my bedroom",
        timeDue: "10:59 pm",
        done: false,
    },
    {    id: 1,
        name: "Clean Kitchen",
        description: "Kitchen needs to be clean",
        timeDue: "7:30 pm",
        done: true,
    },
    {    id: 2,
        name: "Vaccum Floors",
        description: "Floors need to swept/clean",
        timeDue: "2:00 pm",
        done: true,
    },
    {   id: 3,
        name: "Trash",
        description: "Taking out the trash to the trash cans",
        timeDue: "3:00 pm",
        done: true,
    },
    {   id: 4,
        name: "Grocery Store",
        description: "Run to Walmart",
        timeDue: "5:30 pm",
        done: false,
    },
    {   id: 5,
        name: "FInish coding",
        description: "Write out that react jsx",
        timeDue: "5:00 pm",
        done: false
    },
    {   id: 6,
        name: "Drive to store",
        description: "Need to fix my pants",
        timeDue: "3:00 pm",
        done: false
    }
];

export default todoData 